### PR TITLE
Updated description of ls

### PR DESCRIPTION
**Pull request by codephobe**

### CODE REVIEW

**Comment by GabrieleRomeo** [comment]
Jake I think that your description it's not enough strong for the `ls` command

It's a very customizable command, so I think you should provide a more strong description for it

We need to excel man :smile:

**Comment by codephobe** [comment]
Can you reopen these PRs that need to be adjusted?

**Comment by GabrieleRomeo** [comment]
Oh I'm sorry :-)

I'll try to reopen them

2016-03-03 18:27 GMT+01:00 srsjake notifications@github.com:

**Comment by codephobe** [comment]
Thanks. I've updated and expanded the description now.

**Pull request merged**
