### PR TITLE
Added description for mkdir

### PR DESCRIPTION
**Pull request by codephobe**

### CODE REVIEW

**Comment by GabrieleRomeo** [comment]
Variable expansion problem **$**{bold} and **$**{reset}

**Comment by codephobe** [comment]
@GabrieleRomeo Don't close if there's such an error. Makes it hard for me to find it so I can fix it. Just comment and leave it open for me to correct.

**Comment by codephobe** [comment]
Thanks, I've fixed it now.

**Comment by GabrieleRomeo** [comment]
Jake there is the same mistake here `{bold}D{reset}irectory`, please pay more attention to the expansions.

Even though you're a collaborator and you can merge pull requests, please **leave me this task** because I can check your work before. It's just a minimal control, but it can help us!

Thanks

Gabriele

**Pull request merged**
